-- =============================================================================
-- 009 — Catalogue d'import élargi (toutes entités portées)
-- =============================================================================

INSERT INTO import_entity_catalog (entity_type, target_table, depends_on, sort_order, preserve_uuid, org_scoped, description)
VALUES
  ('companies', 'companies', '{organizations,users}', 35, true, true, 'Entreprises liées'),
  ('organization_years', 'organization_years', '{organizations}', 50, true, true, 'Années reporting'),
  ('organization_scope3_subcategories', 'organization_scope3_subcategories', '{organizations}', 55, true, true, 'Sous-catégories Scope 3'),
  ('collect_notifications', 'collect_notifications', '{organizations}', 112, true, true, 'Notifications collect'),
  ('collect_comments', 'collect_comments', '{collect_sessions}', 113, true, true, 'Commentaires collect'),
  ('collect_estimations', 'collect_estimations', '{collect_sessions}', 114, true, true, 'Estimations collect'),
  ('collect_ai_suggestions', 'collect_ai_suggestions', '{collect_sessions}', 115, true, true, 'Suggestions IA collect'),
  ('collect_periodic_history', 'collect_periodic_history', '{collect_sessions}', 116, true, true, 'Historique périodique'),
  ('collect_historical_stats', 'collect_historical_stats', '{organizations}', 117, true, true, 'Stats historiques collect'),
  ('periodic_collections', 'periodic_collections', '{organizations}', 118, true, true, 'Collectes périodiques'),
  ('periodic_collection_executions', 'periodic_collection_executions', '{periodic_collections}', 119, true, true, 'Exécutions périodiques'),
  ('collection_checklist', 'collection_checklist', '{organizations}', 121, true, true, 'Checklist collecte'),
  ('activity_energy', 'activity_energy', '{organizations}', 125, true, true, 'Activité énergie'),
  ('activity_data_to_bilan_detail', 'activity_data_to_bilan_detail', '{activity_data,bilans_carbone_detail}', 175, true, true, 'Lien activité→bilan détail'),
  ('carbon_assessments', 'carbon_assessments', '{organizations,users}', 185, true, true, 'Assessments carbone'),
  ('emissions_totals', 'emissions_totals', '{organizations}', 186, true, true, 'Totaux émissions'),
  ('emission_factors_co2', 'emission_factors_co2', '{}', 141, true, false, 'FE CO2 énergie'),
  ('unit_conversions', 'unit_conversions', '{}', 142, true, false, 'Conversions unités'),
  ('cbam_exports', 'cbam_exports', '{cbam_installations,cbam_products}', 240, true, true, 'Exports CBAM'),
  ('cbam_energy_consumption', 'cbam_energy_consumption', '{cbam_installations}', 241, true, true, 'Énergie CBAM'),
  ('cbam_electricity_consumption', 'cbam_electricity_consumption', '{cbam_installations}', 242, true, true, 'Électricité CBAM'),
  ('cbam_emission_allocation', 'cbam_emission_allocation', '{cbam_installations,cbam_products}', 243, true, true, 'Allocation CBAM'),
  ('cbam_emissions_summary', 'cbam_emissions_summary', '{cbam_installations}', 244, true, true, 'Synthèse CBAM'),
  ('cbam_installation_products', 'cbam_installation_products', '{cbam_installations,cbam_products}', 245, true, true, 'Produits installation CBAM'),
  ('cbam_shipment_emissions', 'cbam_shipment_emissions', '{cbam_exports}', 246, true, true, 'Émissions expédition CBAM'),
  ('pcf_materials', 'pcf_materials', '{pcf_studies}', 330, true, true, 'PCF matières'),
  ('pcf_manufacturing', 'pcf_manufacturing', '{pcf_studies}', 331, true, true, 'PCF fabrication'),
  ('pcf_transport', 'pcf_transport', '{pcf_studies}', 332, true, true, 'PCF transport'),
  ('pcf_packaging', 'pcf_packaging', '{pcf_studies}', 333, true, true, 'PCF emballage'),
  ('pcf_usage', 'pcf_usage', '{pcf_studies}', 334, true, true, 'PCF usage'),
  ('pcf_wastes', 'pcf_wastes', '{pcf_studies}', 335, true, true, 'PCF déchets'),
  ('pcf_end_of_life', 'pcf_end_of_life', '{pcf_studies}', 336, true, true, 'PCF fin de vie'),
  ('pcf_scenarios', 'pcf_scenarios', '{pcf_studies}', 337, true, true, 'PCF scénarios'),
  ('pcf_subcontracting', 'pcf_subcontracting', '{pcf_studies}', 338, true, true, 'PCF sous-traitance'),
  ('pcf_co_product_allocations', 'pcf_co_product_allocations', '{pcf_studies}', 339, true, true, 'PCF co-produits'),
  ('pcf_collect_allocations', 'pcf_collect_allocations', '{pcf_studies,collect_responses}', 340, true, true, 'PCF allocations collect'),
  ('acv_results', 'acv_results', '{acv_projects}', 420, true, true, 'Résultats ACV'),
  ('impact_factors', 'impact_factors', '{}', 421, true, false, 'Facteurs d''impact ACV'),
  ('acv_inventory_settings', 'acv_inventory_settings', '{acv_projects}', 422, true, true, 'Settings inventaire ACV'),
  ('acv_impact_results', 'acv_impact_results', '{organizations}', 423, true, true, 'Résultats impact ACV'),
  ('acv_materials', 'acv_materials', '{}', 424, true, false, 'Matériaux ACV'),
  ('acv_processes', 'acv_processes', '{}', 425, true, false, 'Processus ACV'),
  ('acv_transport_modes', 'acv_transport_modes', '{}', 426, true, false, 'Modes transport ACV'),
  ('acv_product_components', 'acv_product_components', '{acv_projects}', 427, true, true, 'Composants produit ACV'),
  ('acv_lifecycle_modules', 'acv_lifecycle_modules', '{acv_projects}', 428, true, true, 'Modules cycle de vie'),
  ('acv_scenarios', 'acv_scenarios', '{acv_projects}', 429, true, true, 'Scénarios ACV'),
  ('acv_co_products', 'acv_co_products', '{acv_projects}', 430, true, true, 'Co-produits ACV'),
  ('acv_process_flows', 'acv_process_flows', '{acv_projects}', 431, true, true, 'Flux process ACV'),
  ('climate_levers', 'climate_levers', '{climate_roadmaps}', 605, true, true, 'Leviers climat'),
  ('climate_action_milestones', 'climate_action_milestones', '{climate_actions}', 615, true, true, 'Jalons actions climat'),
  ('climate_priority_scores', 'climate_priority_scores', '{climate_actions}', 616, true, true, 'Scores priorité'),
  ('climate_kpis', 'climate_kpis', '{climate_roadmaps}', 617, true, true, 'KPI climat'),
  ('climate_scenarios', 'climate_scenarios', '{organizations}', 620, true, true, 'Scénarios climat'),
  ('climate_scenario_levers', 'climate_scenario_levers', '{climate_scenarios}', 621, true, true, 'Leviers scénario'),
  ('climate_scenario_assumptions', 'climate_scenario_assumptions', '{climate_scenario_levers}', 622, true, true, 'Hypothèses scénario'),
  ('climate_scenario_targets', 'climate_scenario_targets', '{climate_scenarios}', 623, true, true, 'Cibles scénario'),
  ('climate_scenario_results', 'climate_scenario_results', '{climate_scenarios}', 624, true, true, 'Résultats scénario'),
  ('climate_scenario_contributions', 'climate_scenario_contributions', '{climate_scenarios}', 625, true, true, 'Contributions scénario'),
  ('net_zero_trajectories', 'net_zero_trajectories', '{organizations}', 630, true, true, 'Trajectoires net zero'),
  ('supplier_contacts', 'supplier_contacts', '{suppliers}', 505, true, true, 'Contacts fournisseurs'),
  ('supplier_monetary_factors', 'supplier_monetary_factors', '{}', 506, true, false, 'FE monétaires fournisseurs'),
  ('supplier_questionnaires', 'supplier_questionnaires', '{organizations}', 507, true, true, 'Questionnaires fournisseurs'),
  ('supplier_questionnaire_sends', 'supplier_questionnaire_sends', '{supplier_questionnaires,suppliers}', 508, true, true, 'Envois questionnaires'),
  ('supplier_invitations', 'supplier_invitations', '{organizations}', 509, true, true, 'Invitations fournisseurs'),
  ('supplier_score_history', 'supplier_score_history', '{suppliers}', 511, true, true, 'Historique scores fournisseurs'),
  ('supplier_action_plans', 'supplier_action_plans', '{suppliers}', 512, true, true, 'Plans d''action fournisseurs'),
  ('report_templates', 'report_templates', '{}', 701, true, false, 'Templates rapports'),
  ('report_paragraphs', 'report_paragraphs', '{}', 702, true, false, 'Paragraphes rapports'),
  ('report_paragraph_history', 'report_paragraph_history', '{report_paragraphs}', 703, true, false, 'Historique paragraphes'),
  ('report_charts', 'report_charts', '{}', 704, true, false, 'Graphiques rapports'),
  ('report_chart_instances', 'report_chart_instances', '{generated_reports,report_charts}', 705, true, true, 'Instances graphiques'),
  ('report_quota', 'report_quota', '{organizations}', 706, true, true, 'Quotas rapports'),
  ('report_generations', 'report_generations', '{organizations}', 707, true, true, 'Générations rapports'),
  ('courses', 'courses', '{}', 850, true, false, 'Cours academy'),
  ('lessons', 'lessons', '{courses}', 851, true, false, 'Leçons'),
  ('lesson_resources', 'lesson_resources', '{lessons}', 852, true, false, 'Ressources leçons'),
  ('quizzes', 'quizzes', '{lessons}', 853, true, false, 'Quiz'),
  ('quiz_questions', 'quiz_questions', '{quizzes}', 854, true, false, 'Questions quiz'),
  ('user_progress', 'user_progress', '{users,courses}', 855, true, false, 'Progression academy'),
  ('wattbim_buildings', 'wattbim_buildings', '{organizations}', 860, true, true, 'Bâtiments WattBIM'),
  ('wattbim_meters', 'wattbim_meters', '{wattbim_buildings}', 861, true, true, 'Compteurs WattBIM'),
  ('wattbim_readings', 'wattbim_readings', '{wattbim_meters}', 862, true, true, 'Relevés WattBIM'),
  ('wattbim_alerts', 'wattbim_alerts', '{organizations}', 863, true, true, 'Alertes WattBIM'),
  ('wattbim_savings', 'wattbim_savings', '{organizations}', 864, true, true, 'Économies WattBIM'),
  ('wattbim_api_keys', 'wattbim_api_keys', '{organizations}', 865, true, true, 'Clés API WattBIM'),
  ('user_roles', 'user_roles', '{users}', 25, true, false, 'Rôles applicatifs'),
  ('sim_scenarios', 'sim_scenarios', '{organizations}', 870, true, true, 'Scénarios simulation'),
  ('sim_runs', 'sim_runs', '{sim_scenarios}', 871, true, true, 'Runs simulation'),
  ('sim_run_lines', 'sim_run_lines', '{sim_runs}', 872, true, true, 'Lignes runs'),
  ('data_validation_periods', 'data_validation_periods', '{organizations}', 122, true, true, 'Périodes validation')
ON CONFLICT (entity_type) DO UPDATE
SET target_table = EXCLUDED.target_table,
    depends_on = EXCLUDED.depends_on,
    sort_order = EXCLUDED.sort_order,
    description = EXCLUDED.description,
    enabled = true;
