import type { FastifyInstance } from "fastify";
import { registerAuthRoutes } from "./auth.js";
import { registerCalculateRoutes } from "./calculate.js";
import { registerEvidenceRoutes } from "./evidence.js";
import { registerReportRoutes } from "./reports.js";
import { registerLegacyFunctionStubs } from "./legacy-functions.js";
import { registerAdminRoutes } from "./admin.js";
import { registerAdminContentRoutes } from "./adminContent.js";
import { registerOrgRoutes } from "./org.js";
import { registerOrgSettingsRoutes } from "./orgSettings.js";
import { registerCollectRoutes } from "./collect.js";
import { registerBilanRoutes } from "./bilans.js";
import { registerAuditRoutes } from "./audit.js";
import { registerPublicRoutes } from "./public.js";
import { registerImportRoutes } from "./import.js";
import { registerFactorRoutes } from "./factors.js";
import { registerRunRoutes } from "./runs.js";
import { registerCbamRoutes } from "./cbam.js";
import { registerAcvRoutes } from "./acv.js";
import { registerClimateRoutes } from "./climate.js";
import { registerPcfRoutes } from "./pcf.js";
import { registerPrivacyRoutes } from "./privacy.js";
import { registerWebhookRoutes } from "./webhooks.js";
import { registerDiagnosticRoutes } from "./diagnostic.js";

export async function registerRoutes(app: FastifyInstance) {
  await registerAuthRoutes(app);
  await registerPublicRoutes(app);
  await registerDiagnosticRoutes(app);
  await registerWebhookRoutes(app);
  await registerPrivacyRoutes(app);
  await registerImportRoutes(app);
  await registerCalculateRoutes(app);
  await registerEvidenceRoutes(app);
  await registerFactorRoutes(app);
  await registerRunRoutes(app);
  await registerReportRoutes(app);
  await registerAuditRoutes(app);
  await registerAdminRoutes(app);
  await registerAdminContentRoutes(app);
  await registerOrgRoutes(app);
  await registerOrgSettingsRoutes(app);
  await registerCollectRoutes(app);
  await registerBilanRoutes(app);
  await registerCbamRoutes(app);
  await registerPcfRoutes(app);
  await registerAcvRoutes(app);
  await registerClimateRoutes(app);
  await registerLegacyFunctionStubs(app);
}
