import type { AxisId, DiagnosticQuestion, RecommendationRule } from "./types.js";

export const AXES: { id: AxisId; labelFr: string; labelEn: string }[] = [
  { id: "measure", labelFr: "Mesure carbone", labelEn: "Carbon measurement" },
  { id: "energy", labelFr: "Énergie", labelEn: "Energy" },
  { id: "mobility", labelFr: "Mobilité et transport", labelEn: "Mobility and transport" },
  { id: "purchases", labelFr: "Achats et chaîne de valeur", labelEn: "Purchasing and value chain" },
  { id: "steering", labelFr: "Réduction et pilotage", labelEn: "Reduction and steering" },
  { id: "governance", labelFr: "Gouvernance carbone", labelEn: "Carbon governance" },
];

/** Inclusive upper bound. 81–100 is the last open band. */
export const MATURITY_BANDS: { max: number; level: "initial" | "starting" | "structuring" | "managed" | "advanced" }[] = [
  { max: 20, level: "initial" },
  { max: 40, level: "starting" },
  { max: 60, level: "structuring" },
  { max: 80, level: "managed" },
  { max: 100, level: "advanced" },
];

export const LEVEL_LABELS: Record<
  (typeof MATURITY_BANDS)[number]["level"],
  { fr: string; en: string }
> = {
  initial: { fr: "Initial", en: "Initial" },
  starting: { fr: "En démarrage", en: "Getting started" },
  structuring: { fr: "En structuration", en: "Structuring" },
  managed: { fr: "Piloté", en: "Managed" },
  advanced: { fr: "Avancé", en: "Advanced" },
};

export const RELIABILITY_WARNING = {
  fr: "Fiabilité limitée : trop de réponses « Je ne sais pas » ou trop peu de données. Ce niveau accompagne une maturité estimée.",
  en: "Limited reliability: too many “I don't know” answers or too little data. This level accompanies an estimated maturity.",
} as const;

export const RELIABILITY_THRESHOLDS = {
  lowUnknownCount: 4,
  mediumUnknownCount: 2,
  lowUnknownRatio: 0.4,
  mediumUnknownRatio: 0.2,
  lowDataReadiness: 40,
  mediumDataReadiness: 60,
} as const;

const opt = (
  value: string,
  maturity: number | null,
  data: number | null,
  labelFr: string,
  labelEn: string,
) => ({ value, maturity, data, labelFr, labelEn });

export const QUESTIONS: DiagnosticQuestion[] = [
  {
    code: "country",
    axisId: null,
    type: "single",
    weight: 0,
    maturityMax: null,
    dataMax: null,
    unknownExcludesMaturity: false,
    visibility: "always",
    labelFr: "Pays principal d'activité",
    labelEn: "Main country of operation",
    options: [
      opt("TN", null, null, "Tunisie", "Tunisia"),
      opt("EU", null, null, "Union européenne", "European Union"),
      opt("CA", null, null, "Canada", "Canada"),
      opt("OTHER", null, null, "Autre", "Other"),
    ],
  },
  {
    code: "sector",
    axisId: null,
    type: "single",
    weight: 0,
    maturityMax: null,
    dataMax: null,
    unknownExcludesMaturity: false,
    visibility: "always",
    labelFr: "Secteur d'activité",
    labelEn: "Sector",
    options: [
      opt("services", null, null, "Services", "Services"),
      opt("industry", null, null, "Industrie", "Industry"),
      opt("construction", null, null, "Construction", "Construction"),
      opt("trade", null, null, "Commerce", "Trade"),
      opt("transport", null, null, "Transport", "Transport"),
      opt("agrifood", null, null, "Agroalimentaire", "Agri-food"),
      opt("finance", null, null, "Finance", "Finance"),
      opt("other", null, null, "Autre", "Other"),
    ],
  },
  {
    code: "employees",
    axisId: null,
    type: "single",
    weight: 0,
    maturityMax: null,
    dataMax: null,
    unknownExcludesMaturity: false,
    visibility: "always",
    labelFr: "Effectif approximatif",
    labelEn: "Approximate headcount",
    options: [
      opt("lt10", null, null, "Moins de 10", "Fewer than 10"),
      opt("10_49", null, null, "10 à 49", "10 to 49"),
      opt("50_249", null, null, "50 à 249", "50 to 249"),
      opt("250_999", null, null, "250 à 999", "250 to 999"),
      opt("ge1000", null, null, "1 000 et plus", "1,000 or more"),
    ],
  },
  {
    code: "export_status",
    axisId: null,
    type: "single",
    weight: 0,
    maturityMax: null,
    dataMax: null,
    unknownExcludesMaturity: false,
    visibility: "always",
    labelFr: "Exportez-vous des services ou des marchandises ?",
    labelEn: "Do you export services or goods?",
    options: [
      opt("none", null, null, "Non", "No"),
      opt("services_non_eu", null, null, "Services, hors Union européenne", "Services, outside the EU"),
      opt("services_eu", null, null, "Services, vers l'Union européenne", "Services, to the EU"),
      opt("goods_non_eu", null, null, "Marchandises, hors Union européenne", "Goods, outside the EU"),
      opt("goods_eu", null, null, "Marchandises, vers l'Union européenne", "Goods, to the EU"),
      opt("both_non_eu", null, null, "Services et marchandises, hors Union européenne", "Services and goods, outside the EU"),
      opt("both_eu", null, null, "Services et marchandises, vers l'Union européenne", "Services and goods, to the EU"),
    ],
  },
  {
    code: "has_fleet",
    axisId: null,
    type: "single",
    weight: 0,
    maturityMax: null,
    dataMax: null,
    unknownExcludesMaturity: false,
    visibility: "always",
    labelFr: "Disposez-vous d'une flotte de véhicules ?",
    labelEn: "Do you operate a vehicle fleet?",
    options: [
      opt("yes", null, null, "Oui", "Yes"),
      opt("no", null, null, "Non", "No"),
    ],
  },
  {
    code: "has_industrial_site",
    axisId: null,
    type: "single",
    weight: 0,
    maturityMax: null,
    dataMax: null,
    unknownExcludesMaturity: false,
    visibility: "always",
    labelFr: "Exploitez-vous un site de production, un atelier ou une installation technique significative ?",
    labelEn: "Do you operate a production site, a workshop or a significant technical installation?",
    options: [
      opt("yes", null, null, "Oui", "Yes"),
      opt("no", null, null, "Non", "No"),
    ],
  },
  {
    code: "carbon_assessment_status",
    axisId: "measure",
    type: "single",
    weight: 2,
    maturityMax: 3,
    dataMax: null,
    unknownExcludesMaturity: true,
    visibility: "always",
    labelFr: "Avez-vous déjà réalisé un bilan d'émissions de GES ?",
    labelEn: "Have you already completed a GHG inventory?",
    options: [
      opt("never", 0, null, "Jamais", "Never"),
      opt("once", 1, null, "Une fois", "Once"),
      opt("regular", 2, null, "Régulièrement", "Regularly"),
      opt("multi_year", 3, null, "Série pluriannuelle", "Multi-year series"),
      opt("unknown", null, null, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "scopes_covered",
    axisId: "measure",
    type: "multi",
    weight: 2,
    maturityMax: 4,
    dataMax: null,
    unknownExcludesMaturity: true,
    visibility: "assessment_exists",
    labelFr: "Quels périmètres ce bilan couvre-t-il ?",
    labelEn: "Which scopes does that inventory cover?",
    options: [
      opt("s1", 1, null, "Scope 1", "Scope 1"),
      opt("s2", 1, null, "Scope 2", "Scope 2"),
      opt("s3", 2, null, "Scope 3", "Scope 3"),
    ],
  },
  {
    code: "assessment_data_basis",
    axisId: "measure",
    type: "single",
    weight: 2,
    maturityMax: 3,
    dataMax: 3,
    unknownExcludesMaturity: true,
    visibility: "assessment_exists",
    labelFr: "Sur quoi reposent principalement ces données ?",
    labelEn: "What are these data mainly based on?",
    options: [
      opt("estimates", 0, 1, "Estimations", "Estimates"),
      opt("invoices", 1, 2, "Factures ou dépenses", "Invoices or spend"),
      opt("measured", 2, 3, "Mesures (compteurs, km, quantités)", "Measurements"),
      opt("verified", 3, 3, "Mesures vérifiées", "Verified measurements"),
      opt("unknown", null, 0, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "carbon_owner",
    axisId: "measure",
    type: "single",
    weight: 1,
    maturityMax: 2,
    dataMax: null,
    unknownExcludesMaturity: true,
    visibility: "always",
    labelFr: "Qui porte le sujet carbone en interne ?",
    labelEn: "Who owns the carbon topic internally?",
    options: [
      opt("none", 0, null, "Personne", "No one"),
      opt("informal", 1, null, "Une personne, sans mandat formalisé", "Someone, without a formal mandate"),
      opt("named", 2, null, "Un responsable désigné", "A named owner"),
      opt("unknown", null, null, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "energy_tracking",
    axisId: "energy",
    type: "single",
    weight: 2,
    maturityMax: 3,
    dataMax: 3,
    unknownExcludesMaturity: true,
    visibility: "always",
    labelFr: "Comment suivez-vous vos consommations d'énergie ?",
    labelEn: "How do you track energy use?",
    options: [
      opt("none", 0, 0, "Pas de suivi", "No tracking"),
      opt("annual", 1, 1, "Total annuel", "Annual total"),
      opt("monthly", 2, 2, "Suivi mensuel", "Monthly tracking"),
      opt("by_site", 3, 3, "Suivi mensuel par site", "Monthly tracking by site"),
      opt("unknown", null, 0, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "energy_target",
    axisId: "energy",
    type: "single",
    weight: 1,
    maturityMax: 2,
    dataMax: null,
    unknownExcludesMaturity: true,
    visibility: "no_industrial_site",
    labelFr: "Avez-vous un objectif de réduction d'énergie ?",
    labelEn: "Do you have an energy reduction target?",
    options: [
      opt("none", 0, null, "Non", "No"),
      opt("qualitative", 1, null, "Oui, qualitatif", "Yes, qualitative"),
      opt("quantified", 2, null, "Oui, chiffré", "Yes, quantified"),
      opt("unknown", null, null, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "energy_audit",
    axisId: "energy",
    type: "single",
    weight: 1,
    maturityMax: 2,
    dataMax: null,
    unknownExcludesMaturity: true,
    visibility: "industrial_site",
    labelFr: "Un audit énergétique a-t-il été réalisé ?",
    labelEn: "Has an energy audit been carried out?",
    options: [
      opt("never", 0, null, "Non", "No"),
      opt("old", 1, null, "Oui, il y a plus de 3 ans", "Yes, more than 3 years ago"),
      opt("recent", 2, null, "Oui, depuis moins de 3 ans", "Yes, within 3 years"),
      opt("unknown", null, null, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "fleet_fuel_tracking",
    axisId: "mobility",
    type: "single",
    weight: 1,
    maturityMax: 2,
    dataMax: 2,
    unknownExcludesMaturity: true,
    visibility: "has_fleet",
    labelFr: "Comment suivez-vous les carburants de la flotte ?",
    labelEn: "How do you track fleet fuel?",
    options: [
      opt("none", 0, 0, "Pas de suivi", "No tracking"),
      opt("invoices", 1, 1, "Factures de carburant", "Fuel invoices"),
      opt("km_and_fuel", 2, 2, "Kilomètres et litres", "Kilometres and litres"),
      opt("unknown", null, 0, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "business_travel_tracking",
    axisId: "mobility",
    type: "single",
    weight: 1,
    maturityMax: 2,
    dataMax: 2,
    unknownExcludesMaturity: true,
    visibility: "no_fleet",
    labelFr: "Suivez-vous les déplacements professionnels ?",
    labelEn: "Do you track business travel?",
    options: [
      opt("none", 0, 0, "Non", "No"),
      opt("partial", 1, 1, "Partiellement", "Partly"),
      opt("systematic", 2, 2, "Oui, de façon systématique", "Yes, systematically"),
      opt("unknown", null, 0, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "purchase_data",
    axisId: "purchases",
    type: "single",
    weight: 2,
    maturityMax: 3,
    dataMax: 3,
    unknownExcludesMaturity: true,
    visibility: "always",
    labelFr: "De quelles données achats disposez-vous ?",
    labelEn: "What purchasing data do you have?",
    options: [
      opt("none", 0, 0, "Aucune donnée exploitable", "No usable data"),
      opt("total_spend", 1, 1, "Dépense totale", "Total spend"),
      opt("by_category", 2, 2, "Dépense par catégorie", "Spend by category"),
      opt("by_supplier", 3, 3, "Dépense par fournisseur", "Spend by supplier"),
      opt("unknown", null, 0, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "supplier_carbon",
    axisId: "purchases",
    type: "single",
    weight: 2,
    maturityMax: 2,
    dataMax: 2,
    unknownExcludesMaturity: true,
    visibility: "always",
    labelFr: "Disposez-vous de données carbone de vos fournisseurs ?",
    labelEn: "Do you have carbon data from suppliers?",
    options: [
      opt("none", 0, 0, "Non", "No"),
      opt("some", 1, 1, "Pour quelques fournisseurs", "For a few suppliers"),
      opt("systematic", 2, 2, "Oui, de façon systématique", "Yes, systematically"),
      opt("unknown", null, 0, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "scope3_posture",
    axisId: "purchases",
    type: "single",
    weight: 2,
    maturityMax: 2,
    dataMax: 2,
    unknownExcludesMaturity: true,
    visibility: "scope3_slot",
    labelFr: "Comment traitez-vous le Scope 3 aujourd'hui ?",
    labelEn: "How do you handle Scope 3 today?",
    options: [
      opt("not_started", 0, 0, "Pas commencé", "Not started"),
      opt("spend", 1, 1, "Approche par les dépenses", "Spend-based"),
      opt("activity", 2, 2, "Approche par les quantités", "Activity-based"),
      opt("unknown", null, 0, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "review_cadence",
    axisId: "steering",
    type: "single",
    weight: 1,
    maturityMax: 2,
    dataMax: null,
    unknownExcludesMaturity: true,
    visibility: "review_slot",
    labelFr: "À quel rythme revoyez-vous vos données carbone ou énergie ?",
    labelEn: "How often do you review carbon or energy data?",
    options: [
      opt("never", 0, null, "Jamais", "Never"),
      opt("annual", 1, null, "Une fois par an", "Once a year"),
      opt("quarterly", 2, null, "Au moins chaque trimestre", "At least quarterly"),
      opt("unknown", null, null, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "reduction_target",
    axisId: "steering",
    type: "single",
    weight: 2,
    maturityMax: 2,
    dataMax: null,
    unknownExcludesMaturity: true,
    visibility: "always",
    labelFr: "Avez-vous un objectif de réduction des émissions ?",
    labelEn: "Do you have an emissions reduction target?",
    options: [
      opt("none", 0, null, "Non", "No"),
      opt("qualitative", 1, null, "Oui, sans chiffre", "Yes, without a figure"),
      opt("quantified", 2, null, "Oui, chiffré", "Yes, quantified"),
      opt("unknown", null, null, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "action_plan",
    axisId: "steering",
    type: "single",
    weight: 2,
    maturityMax: 2,
    dataMax: null,
    unknownExcludesMaturity: true,
    visibility: "always",
    labelFr: "Existe-t-il un plan d'actions ?",
    labelEn: "Is there an action plan?",
    options: [
      opt("none", 0, null, "Non", "No"),
      opt("list", 1, null, "Une liste d'actions", "A list of actions"),
      opt("owned_budgeted", 2, null, "Actions avec responsable et budget", "Actions with an owner and a budget"),
      opt("unknown", null, null, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "client_requirements",
    axisId: "governance",
    type: "single",
    weight: 0,
    maturityMax: null,
    dataMax: null,
    unknownExcludesMaturity: false,
    visibility: "always",
    labelFr: "Vos clients demandent-ils des informations carbone ?",
    labelEn: "Do customers ask for carbon information?",
    options: [
      opt("none", null, null, "Non", "No"),
      opt("occasional", null, null, "Parfois", "Sometimes"),
      opt("contractual", null, null, "Oui, de façon contractuelle", "Yes, contractually"),
      opt("unknown", null, null, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "cbam_exposure",
    axisId: "governance",
    type: "single",
    weight: 1,
    maturityMax: 2,
    dataMax: null,
    unknownExcludesMaturity: true,
    visibility: "cbam_slot",
    labelFr: "Vos marchandises exportées vers l'UE pourraient-elles relever des catégories couvertes par le MACF ?",
    labelEn: "Could your goods exported to the EU fall within CBAM covered categories?",
    options: [
      opt("not_examined", 0, null, "Pas encore examiné", "Not examined yet"),
      opt("possible", 1, null, "C'est possible, sans vérification aboutie", "Possible, without a completed check"),
      opt("mapped", 2, null, "Catégories vérifiées", "Categories checked"),
      opt("unknown", null, null, "Je ne sais pas", "I don't know"),
    ],
  },
  {
    code: "carbon_reporting",
    axisId: "governance",
    type: "single",
    weight: 1,
    maturityMax: 2,
    dataMax: null,
    unknownExcludesMaturity: true,
    visibility: "reporting_slot",
    labelFr: "Publiez-vous un suivi carbone ?",
    labelEn: "Do you report on carbon?",
    options: [
      opt("none", 0, null, "Non", "No"),
      opt("internal", 1, null, "Suivi interne", "Internal reporting"),
      opt("external", 2, null, "Communication externe", "External reporting"),
      opt("unknown", null, null, "Je ne sais pas", "I don't know"),
    ],
  },
];

export const RECOMMENDATIONS: RecommendationRule[] = [
  {
    id: "no_ghg_inventory",
    axisId: "measure",
    priority: "high",
    module: "bilan",
    conditionKey: "assessment_never",
    moduleIfSector: { finance: "pcaf" },
    titleFr: "Réaliser une première mesure structurée",
    titleEn: "Complete a first structured inventory",
    bodyFr: "Réaliser une première mesure structurée de vos émissions de GES, sans la confondre avec ce pré-diagnostic.",
    bodyEn: "Complete a first structured GHG inventory. This pre-diagnostic is not that inventory.",
    when: (answers) => choice(answers, "carbon_assessment_status") === "never",
  },
  {
    id: "cbam_verify_exposure",
    axisId: "governance",
    priority: "high",
    module: "cbam",
    conditionKey: "goods_eu_exposure_unverified",
    titleFr: "Vérifier votre exposition au MACF",
    titleEn: "Check your CBAM exposure",
    bodyFr: "Ce pré-diagnostic n'établit pas l'applicabilité du MACF. Vérifier si les marchandises exportées vers l'Union européenne relèvent des catégories couvertes.",
    bodyEn: "This pre-diagnostic does not establish whether CBAM applies. Check whether the goods exported to the European Union fall within the covered categories.",
    when: (answers, ctx) => {
      if (!ctx.visible.has("cbam_exposure")) return false;
      const answer = answers.cbam_exposure;
      if (!answer || answer.kind === "unknown") return true;
      return answer.kind === "choice" && (answer.value === "not_examined" || answer.value === "possible");
    },
  },
  {
    id: "incomplete_scopes",
    axisId: "measure",
    priority: "high",
    module: "collect",
    conditionKey: "scopes_without_s3",
    titleFr: "Couvrir le Scope 3 dans la mesure",
    titleEn: "Cover Scope 3 in the inventory",
    bodyFr: "Le bilan existant ne couvre pas le Scope 3. Structurer les postes significatifs avant d'élargir le chiffre.",
    bodyEn: "The existing inventory does not cover Scope 3. Structure the material categories before extending the figure.",
    when: (answers, ctx) =>
      ctx.visible.has("scopes_covered") && !selected(answers, "scopes_covered").includes("s3"),
  },
  {
    id: "scope3_gap",
    axisId: "purchases",
    priority: "high",
    module: "collect",
    conditionKey: "weak_value_chain",
    titleFr: "Structurer les données achats et Scope 3",
    titleEn: "Structure purchasing and Scope 3 data",
    bodyFr: "Structurer la collecte des achats, déplacements et autres postes significatifs du Scope 3.",
    bodyEn: "Structure collection for purchasing, travel and other material Scope 3 categories.",
    when: (answers) => {
      const purchase = choice(answers, "purchase_data");
      const supplier = choice(answers, "supplier_carbon");
      const posture = choice(answers, "scope3_posture");
      return (
        purchase === "none" ||
        purchase === "total_spend" ||
        purchase === "unknown" ||
        supplier === "none" ||
        supplier === "unknown" ||
        posture === "not_started" ||
        posture === "unknown"
      );
    },
  },
  {
    id: "no_reduction_target",
    axisId: "steering",
    priority: "high",
    module: "bilan",
    conditionKey: "reduction_none",
    titleFr: "Poser un objectif de réduction après la mesure",
    titleEn: "Set a reduction target after measuring",
    bodyFr: "Un objectif de réduction se fixe sur une mesure réelle, pas sur ce pré-diagnostic.",
    bodyEn: "A reduction target should sit on a real inventory, not on this pre-diagnostic.",
    when: (answers) => choice(answers, "reduction_target") === "none",
  },
  {
    id: "no_named_owner",
    axisId: "measure",
    priority: "medium",
    module: "bilan",
    conditionKey: "owner_none",
    titleFr: "Désigner un responsable carbone",
    titleEn: "Name a carbon owner",
    bodyFr: "Désigner un responsable interne, avec un mandat explicite.",
    bodyEn: "Name an internal owner, with an explicit mandate.",
    when: (answers) => choice(answers, "carbon_owner") === "none",
  },
  {
    id: "weak_activity_data",
    axisId: "measure",
    priority: "medium",
    module: "collect",
    conditionKey: "basis_estimates",
    titleFr: "Remplacer les estimations par des données mesurées",
    titleEn: "Replace estimates with measured data",
    bodyFr: "Le bilan repose encore surtout sur des estimations. Passer aux factures, compteurs et quantités.",
    bodyEn: "The inventory still relies mainly on estimates. Move to invoices, meters and quantities.",
    when: (answers, ctx) =>
      ctx.visible.has("assessment_data_basis") && choice(answers, "assessment_data_basis") === "estimates",
  },
  {
    id: "energy_not_tracked",
    axisId: "energy",
    priority: "medium",
    module: "history",
    conditionKey: "energy_none_or_unknown",
    moduleIfIndustrialSite: "wattbim",
    titleFr: "Mettre en place un suivi énergétique périodique",
    titleEn: "Set up periodic energy tracking",
    bodyFr: "Suivre l'énergie au moins chaque mois, avant d'ajouter des équipements.",
    bodyEn: "Track energy at least monthly, before adding equipment.",
    when: (answers) => {
      const v = choice(answers, "energy_tracking");
      return v === "none" || v === "unknown";
    },
  },
  {
    id: "plan_not_owned",
    axisId: "steering",
    priority: "medium",
    module: "history",
    conditionKey: "plan_list",
    titleFr: "Rattacher chaque action à un responsable",
    titleEn: "Attach each action to an owner",
    bodyFr: "La liste d'actions existe. Lui ajouter un responsable et un moyen de suivi.",
    bodyEn: "An action list exists. Add an owner and a way to follow it.",
    when: (answers) => choice(answers, "action_plan") === "list",
  },
  {
    id: "no_periodic_review",
    axisId: "steering",
    priority: "medium",
    module: "history",
    conditionKey: "review_never",
    titleFr: "Mettre en place un suivi périodique",
    titleEn: "Set up a periodic review",
    bodyFr: "Revoir les données au moins une fois par an, sur les mêmes périmètres.",
    bodyEn: "Review the data at least once a year, on the same boundaries.",
    when: (answers, ctx) => ctx.visible.has("review_cadence") && choice(answers, "review_cadence") === "never",
  },
  {
    id: "maintain_cycle",
    axisId: "steering",
    priority: "low",
    module: "history",
    conditionKey: "maturity_at_least_80_without_high",
    titleFr: "Tenir le rythme de mesure et de revue",
    titleEn: "Keep the measurement and review cycle",
    bodyFr: "Le dispositif est avancé. Le maintenir sur la même méthode, d'une campagne à l'autre.",
    bodyEn: "The system is advanced. Keep the same method from one campaign to the next.",
    when: () => false,
  },
];

function choice(answers: Parameters<RecommendationRule["when"]>[0], code: string): string | null {
  const answer = answers[code];
  if (!answer || answer.kind !== "choice") return null;
  return answer.value;
}

function selected(answers: Parameters<RecommendationRule["when"]>[0], code: string): string[] {
  const answer = answers[code];
  if (!answer || answer.kind !== "multi") return [];
  return answer.values;
}

export function questionByCode(code: string): DiagnosticQuestion {
  const found = QUESTIONS.find((question) => question.code === code);
  if (!found) throw new Error(`Unknown diagnostic question: ${code}`);
  return found;
}
